# Generated by Django 6.0.6 on 2026-07-09 22:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_options_profile_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='شماره تلفن باید با 09 شروع شود و 11 رقم باشد', regex='^09\\d{9}$')]),
        ),
    ]
