# Generated by Django 6.0.6 on 2026-07-01 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_bannerslide_category_homesettings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerslide',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='عنوان'),
        ),
    ]
