# Generated by Django 6.0.6 on 2026-07-01 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_bannerslide_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerslide',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, verbose_name='عنوان مشخصه')),
                ('value', models.CharField(max_length=200, verbose_name='مقدار مشخصه')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='shop.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'مشخصه محصول',
                'verbose_name_plural': 'مشخصات محصول',
                'ordering': ['order'],
            },
        ),
    ]
