# Generated by Django 6.0.6 on 2026-07-01 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_bannerslide_title_productspecification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='about_product',
            field=models.TextField(blank=True, help_text='توضیحات فنی، نحوه ساخت، جنس و مشخصات محصول', verbose_name='درباره محصول'),
        ),
        migrations.AddField(
            model_name='product',
            name='character_story',
            field=models.TextField(blank=True, help_text='بیوگرافی و داستان شخصیت', verbose_name='داستان شخصیت'),
        ),
    ]
