# Generated by Django 6.0.6 on 2026-07-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_product_description_product_about_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='تصویر بنر بالای صفحه محصول (ابعاد پیشنهادی: 1200x400)', null=True, upload_to='product_banners/', verbose_name='تصویر بنر محصول'),
        ),
        migrations.AddField(
            model_name='product',
            name='banner_subtitle',
            field=models.CharField(blank=True, help_text='زیرنویسی که روی بنر نمایش داده میشه', max_length=300, verbose_name='زیرنویس بنر'),
        ),
        migrations.AddField(
            model_name='product',
            name='banner_title',
            field=models.CharField(blank=True, help_text='عنوانی که روی بنر نمایش داده میشه', max_length=200, verbose_name='عنوان بنر'),
        ),
    ]
