# Generated by Django 6.0.6 on 2026-07-01 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_product_banner_image_product_banner_subtitle_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="homesettings",
            name="hero_banner_height",
            field=models.CharField(
                default="100vh",
                help_text="مثلاً: 100vh یا 600px",
                max_length=20,
                verbose_name="ارتفاع بنر",
            ),
        ),
        migrations.AddField(
            model_name="homesettings",
            name="hero_banner_overlay_opacity",
            field=models.CharField(
                default="0.6",
                help_text="0 تا 1",
                max_length=20,
                verbose_name="شفافیت لایه رویی",
            ),
        ),
        migrations.AddField(
            model_name="homesettings",
            name="hero_subtitle_color",
            field=models.CharField(
                default="rgba(255,255,255,0.7)",
                max_length=255,
                verbose_name="رنگ زیرنویس",
            ),
        ),
        migrations.AddField(
            model_name="homesettings",
            name="hero_subtitle_font_size",
            field=models.CharField(
                default="20px", max_length=20, verbose_name="اندازه فونت زیرنویس"
            ),
        ),
        migrations.AddField(
            model_name="homesettings",
            name="hero_title_color",
            field=models.CharField(
                default="#ffffff",
                help_text="مثلاً: #ffffff یا red",
                max_length=20,
                verbose_name="رنگ عنوان اصلی",
            ),
        ),
        migrations.AddField(
            model_name="homesettings",
            name="hero_title_first_word_color",
            field=models.CharField(
                default="#c1121f",
                help_text="رنگ کلمه اول (مثلاً FIGMAX)",
                max_length=20,
                verbose_name="رنگ کلمه اول",
            ),
        ),
        migrations.AddField(
            model_name="homesettings",
            name="hero_title_font_size",
            field=models.CharField(
                default="72px",
                help_text="مثلاً: 72px یا 4rem",
                max_length=20,
                verbose_name="اندازه فونت عنوان",
            ),
        ),
        migrations.AddField(
            model_name="homesettings",
            name="hero_title_font_weight",
            field=models.CharField(
                default="900",
                help_text="100 تا 900",
                max_length=20,
                verbose_name="ضخامت فونت عنوان",
            ),
        ),
        migrations.AddField(
            model_name="homesettings",
            name="hero_title_second_word_color",
            field=models.CharField(
                default="#ffffff",
                help_text="رنگ کلمه دوم (مثلاً SHOP)",
                max_length=20,
                verbose_name="رنگ کلمه دوم",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="banner_height",
            field=models.CharField(
                blank=True,
                default="400",
                help_text="مثلاً: 400 یا 500 یا 300",
                max_length=20,
                verbose_name="ارتفاع بنر (پیکسل)",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="banner_object_fit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cover", "پوشش کامل (cover)"),
                    ("contain", "نمایش کامل (contain)"),
                    ("fill", "پر کردن (fill)"),
                ],
                default="cover",
                max_length=20,
                verbose_name="نحوه نمایش تصویر",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="banner_image",
            field=models.ImageField(
                blank=True,
                help_text="تصویر بنر بالای صفحه محصول",
                null=True,
                upload_to="product_banners/",
                verbose_name="تصویر بنر محصول",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="banner_subtitle",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="زیرنویس بنر"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="banner_title",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="عنوان بنر"
            ),
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True, max_length=40, null=True, verbose_name="کلید نشست"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "سبد خرید",
                "verbose_name_plural": "سبدهای خرید",
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="تعداد"),
                ),
                (
                    "added_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاریخ اضافه شدن"
                    ),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="shop.cart",
                        verbose_name="سبد خرید",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop.product",
                        verbose_name="محصول",
                    ),
                ),
            ],
            options={
                "verbose_name": "آیتم سبد خرید",
                "verbose_name_plural": "آیتم\u200cهای سبد خرید",
                "unique_together": {("cart", "product")},
            },
        ),
    ]
