# Generated by Django 6.0.6 on 2026-07-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_homesettings_hero_banner_height_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='banner_height',
        ),
        migrations.RemoveField(
            model_name='product',
            name='banner_object_fit',
        ),
        migrations.AlterField(
            model_name='product',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='تصویر بنر بالای صفحه محصول (سایز پیشنهادی: 1200x400)', null=True, upload_to='product_banners/', verbose_name='تصویر بنر محصول'),
        ),
    ]
