# Generated by Django 6.0.6 on 2026-07-03 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_product_banner_height_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimilarProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_products', to='shop.product', verbose_name='محصول اصلی')),
                ('similar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_to', to='shop.product', verbose_name='محصول مشابه')),
            ],
            options={
                'verbose_name': 'محصول مشابه',
                'verbose_name_plural': 'محصولات مشابه',
                'ordering': ['order'],
                'unique_together': {('product', 'similar')},
            },
        ),
    ]
