# Generated by Django 6.0.6 on 2026-07-08 21:50

import apps.shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_product_title_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, help_text='تاریخی که سفارش به دست مشتری رسیده است', null=True, verbose_name='تاریخ تحویل'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_code',
            field=models.CharField(blank=True, help_text='کد پیگیری مرسوله پستی یا کد رهگیری', max_length=100, null=True, verbose_name='کد پیگیری'),
        ),
        migrations.AlterField(
            model_name='bannerslide',
            name='image',
            field=models.ImageField(upload_to='banners/', validators=[apps.shop.models.validate_image_size, apps.shop.models.validate_image_extension], verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='product',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='تصویر بنر بالای صفحه محصول (سایز پیشنهادی: 1200x400، حداکثر 5 مگابایت)', null=True, upload_to='product_banners/', validators=[apps.shop.models.validate_image_size, apps.shop.models.validate_image_extension], verbose_name='تصویر بنر محصول'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/', validators=[apps.shop.models.validate_image_size, apps.shop.models.validate_image_extension], verbose_name='تصویر'),
        ),
    ]
