# Generated by Django 6.0.6 on 2026-07-08 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_order_delivered_at_order_tracking_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homesettings',
            name='cta_background_image',
            field=models.ImageField(blank=True, help_text='تصویر بنر CTA (سایز پیشنهادی: 1200x600)', null=True, upload_to='cta/', verbose_name='تصویر پس\u200cزمینه CTA'),
        ),
        migrations.AddField(
            model_name='homesettings',
            name='cta_border_radius',
            field=models.CharField(default='30px', max_length=20, verbose_name='گردی گوشه\u200cهای CTA'),
        ),
        migrations.AddField(
            model_name='homesettings',
            name='cta_button_color',
            field=models.CharField(default='#c1121f', max_length=20, verbose_name='رنگ دکمه CTA'),
        ),
        migrations.AddField(
            model_name='homesettings',
            name='cta_button_link',
            field=models.CharField(blank=True, default='/products/', max_length=200, verbose_name='لینک دکمه CTA'),
        ),
        migrations.AddField(
            model_name='homesettings',
            name='cta_button_text_color',
            field=models.CharField(default='#ffffff', max_length=20, verbose_name='رنگ متن دکمه CTA'),
        ),
        migrations.AddField(
            model_name='homesettings',
            name='cta_height',
            field=models.CharField(default='450px', max_length=20, verbose_name='ارتفاع بنر CTA'),
        ),
        migrations.AddField(
            model_name='homesettings',
            name='cta_overlay_opacity',
            field=models.CharField(default='0.7', max_length=20, verbose_name='شفافیت لایه رویی CTA'),
        ),
        migrations.AddField(
            model_name='homesettings',
            name='cta_subtitle',
            field=models.CharField(blank=True, default='با فیگورهای منحصر\u200cبه\u200cفرد ما، کلکسیون خود را بی\u200cنظیر کنید', max_length=300, verbose_name='زیرنویس CTA'),
        ),
        migrations.AddField(
            model_name='homesettings',
            name='cta_subtitle_color',
            field=models.CharField(default='#cccccc', max_length=20, verbose_name='رنگ زیرنویس CTA'),
        ),
        migrations.AddField(
            model_name='homesettings',
            name='cta_title_color',
            field=models.CharField(default='#ffffff', max_length=20, verbose_name='رنگ عنوان CTA'),
        ),
        migrations.AddField(
            model_name='homesettings',
            name='featured_products_subtitle',
            field=models.CharField(blank=True, default='مجموعه\u200cای از نفیس\u200cترین فیگورهای کلکسیونی', max_length=200, verbose_name='زیرنویس بخش محصولات ویژه'),
        ),
        migrations.AddField(
            model_name='homesettings',
            name='features_title',
            field=models.CharField(blank=True, default='چرا فیگمکس؟', max_length=100, verbose_name='عنوان بخش ویژگی\u200cها'),
        ),
        migrations.AddField(
            model_name='homesettings',
            name='footer_copyright',
            field=models.CharField(blank=True, default='© 2026 FIGMAX', max_length=200, verbose_name='متن کپی\u200cرایت'),
        ),
        migrations.AddField(
            model_name='homesettings',
            name='hero_background_image',
            field=models.ImageField(blank=True, help_text='تصویر بنر اصلی (سایز پیشنهادی: 1920x1080)', null=True, upload_to='hero/', verbose_name='تصویر پس\u200cزمینه هیرو'),
        ),
        migrations.AddField(
            model_name='homesettings',
            name='show_features_section',
            field=models.BooleanField(default=True, verbose_name='نمایش بخش ویژگی\u200cها'),
        ),
        migrations.AddField(
            model_name='homesettings',
            name='site_description',
            field=models.CharField(blank=True, default='مرجع تخصصی فیگورهای کلکسیونی', max_length=300, verbose_name='توضیحات سایت'),
        ),
        migrations.AddField(
            model_name='homesettings',
            name='site_name',
            field=models.CharField(default='FIGMAX', max_length=100, verbose_name='نام سایت'),
        ),
        migrations.AlterField(
            model_name='homesettings',
            name='cta_title',
            field=models.CharField(default='کلکسیون خود را کامل کنید', max_length=200, verbose_name='عنوان CTA'),
        ),
        migrations.AlterField(
            model_name='homesettings',
            name='hero_banner_height',
            field=models.CharField(default='100vh', max_length=20, verbose_name='ارتفاع بنر'),
        ),
        migrations.AlterField(
            model_name='homesettings',
            name='hero_banner_overlay_opacity',
            field=models.CharField(default='0.6', max_length=20, verbose_name='شفافیت لایه رویی'),
        ),
        migrations.AlterField(
            model_name='homesettings',
            name='hero_title_color',
            field=models.CharField(default='#ffffff', max_length=20, verbose_name='رنگ عنوان اصلی'),
        ),
        migrations.AlterField(
            model_name='homesettings',
            name='hero_title_first_word_color',
            field=models.CharField(default='#c1121f', max_length=20, verbose_name='رنگ کلمه اول'),
        ),
        migrations.AlterField(
            model_name='homesettings',
            name='hero_title_font_size',
            field=models.CharField(default='72px', max_length=20, verbose_name='اندازه فونت عنوان'),
        ),
        migrations.AlterField(
            model_name='homesettings',
            name='hero_title_font_weight',
            field=models.CharField(default='900', max_length=20, verbose_name='ضخامت فونت عنوان'),
        ),
        migrations.AlterField(
            model_name='homesettings',
            name='hero_title_second_word_color',
            field=models.CharField(default='#ffffff', max_length=20, verbose_name='رنگ کلمه دوم'),
        ),
    ]
