# Generated by Django 6.0.6 on 2026-07-08 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_homesettings_cta_background_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerslide',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='زیرنویس'),
        ),
        migrations.AlterField(
            model_name='bannerslide',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان'),
        ),
    ]
