# Generated by Django 6.0.6 on 2026-09-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_bannerslide_subtitle_alter_bannerslide_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homesettings',
            name='hero_subtitle_color',
            field=models.CharField(default='rgba(255,255,255,0.7)', max_length=50, verbose_name='رنگ زیرنویس'),
        ),
    ]
